name: Create Release

on:
  repository_dispatch:
    types: [release]
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Install .NET 9
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Install NGBV
      uses: dotnet/nbgv@master
      id: nbgv
    - name: Push git changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        tags: true
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        body: ${{ steps.changelog.outputs.clean_changelog }}
        tag_name: ${{ steps.nbgv.outputs.Version }}
        name: ${{ steps.nbgv.outputs.Version }}
        draft: false
        prerelease: false
        generate_release_notes: true
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
